### PR TITLE
Add support for Python 3.7.

### PR DESCRIPTION
**Pull request by jamadden**
Rename .txt -> .rst

### CODE REVIEW

**Comment by jamadden** [comment]
Because of [github's issues](https://blog.github.com/2018-10-21-october21-incident-report/), we don't have CI runs of this yet. Hopefully they will get unpaused soon because I'd prefer to wait for successful CI before merging and releasing.

**Comment by mgedmin** [comment]
(GitHub's brokenness is why I reviewed this PR twice ;)

**Comment by jamadden** [comment]
Thanks! Travis is showing green (although the checkmarks haven't updated on this page for me). Could we please get a release? (Or access for `jamadden`)

**Comment by mgedmin** [comment]
You have the PyPI bit now

**Comment by jamadden** [comment]
Thanks! 4.1.0 has been pushed to PyPI.

**Pull request merged**
